# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SoqQiEWqo6iwZ9PP05CZ3YbNCtkBtrIa
"""

! pip install streamlit -q

pip install google-generativeai

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

import google.generativeai as palm

palm.configure(api_key="AIzaSyCJMk65bThdYsPcqbZsBy1xoDGoDz-s1hw")

defaults = {
    'model': 'models/text-bison-001',
    'temperature': 0.7,
    'candidate_count': 1,
    'top_k': 40,
    'top_p': 0.95,
    'max_output_tokens': 1024,
}

# import the streamlit library
import streamlit as st

# give a title to our app
st.title('Welcome to The Explanation Code !')

# Selection box
PLanguage = st.selectbox("Choose the programming language: ", ['C++', 'Java', 'Python', 'PHP', 'Javascript', 'R'])

# Selection box
OLanguage = st.selectbox("Choose the output language: ", ['English', 'Bahasa'])

# Text Input
input_code = st.text_area("What code do you want me to explain :) ?", height=200)

# # Use Streamlit caching to avoid re-generating text on every button click
# @st.cache_data

# Fungsi generate response
def generate_response(prompt):
    response = palm.generate_text(**defaults, prompt=prompt)
    return response.result if response else ''

# prompt to generate text
prompt = f"Can you explain the following {PLanguage} code to me:\n\n{input_code}. Explain using {OLanguage} and if possible explain it more detail !"

# display the name when the submit button is clicked
if st.button('Submit'):
    response_text = generate_response(prompt)
    st.markdown(f"<div style='width: 705px; white-space: pre-wrap; text-align: justify;'>{response_text}</div>", unsafe_allow_html=True)

""" Contoh Code

llm\_data %>%
 ggplot(aes(x=Training\_Data,y=Params, label=Model))+
 geom\_label()+
 labs(
 x= "Training Data (billion tokens)",
 y= "Parameters (billions)"
 )+
 theme\_bw()